### ISSUE TITLE
正在下载的视频可不可以改下不会被自动清除删掉

### ISSUE THREAD

**Issue by abcdpm** [develon2015/Youtube-dl-REST#16]
在 https://y2b.123345.xyz/ 上下载视频的时候快下好的时候突然没了，被拒绝访问了

**Comment by develon2015** [comment]
好的，可以考虑！

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："lIlIAIex "<notifications@github.com&gt;;
发送时间：2020年11月12日(星期四) 凌晨0:16
收件人："develon2015/Youtube-dl-REST" <Youtube-dl-REST@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[develon2015/Youtube-dl-REST] 正在下载的视频可不可以改下不会被自动清除删掉 (#16)
-----------------------------------

 

 
在 https://y2b.123345.xyz/ 上下载视频的时候快下好的时候突然没了，被拒绝访问了
