### ISSUE TITLE
请问如何加载HTTPS

### ISSUE THREAD

**Issue by cdkeyleo** [develon2015/Youtube-dl-REST#19]
我在自己的Linux上安装了Youtube-dl-REST，
现在可以访问Linux设备IP地址80端口进行下载，
但是我希望Youtube-dl-REST运行在HTTPS上，
能否给点提示？

**Comment by develon2015** [comment]
有自己的域名和证书的话，使用 nginx 进行反向代理即可。
没有的话可以使用CDN，例如CloudFlare。

**Comment by cdkeyleo** [comment]
赞，好办法
