### ISSUE TITLE
自己搭建bilibili最高分辨率只能解析480

### ISSUE THREAD

**Issue by love2wind** [develon2015/Youtube-dl-REST#30]
是不是要加入自己的cookie？
![image](https://github.com/develon2015/Youtube-dl-REST/assets/11996852/278f969d-aad4-4206-a379-71875fd6a24a)
同一是视频在演示站就可以解析1080
![image](https://github.com/develon2015/Youtube-dl-REST/assets/11996852/864d824d-6922-4287-95b3-7e10495b8df8)

**Comment by develon2015** [comment]
是的, 登录自己的账号后, 使用 Get cookies.txt LOCALLY 这个浏览器插件复制cookies

**Comment by love2wind** [comment]
好的，搞定了，感谢。另外希望能支持docker，能方便点。
