### ISSUE TITLE
现在已经无法使用了吗

### ISSUE THREAD

**Issue by xiao-j-c** [develon2015/Youtube-dl-REST#41]
提示
Error: Command failed: yt-dlp --print-json --skip-download --cookies cookies.txt 'https://www.youtube.com/watch?v=fK6vFhoDDzA' 2> /dev/null

**Comment by develon2015** [comment]
检查 cookies.txt 文件

登录自己的账号后, 使用 Get cookies.txt LOCALLY 这个浏览器插件复制cookies

**Comment by xiao-j-c** [comment]
是这样操作的，还是提示这个错误信息

**Comment by xiao-j-c** [comment]
是我的账号不行了?

**Comment by develon2015** [comment]
升级一下yt-dlp:

```
sudo yt-dlp -U
```

**Comment by xiao-j-c** [comment]
可以了，感谢大佬
