### ISSUE TITLE
最近下载好慢怎么回事，时常断开

### ISSUE THREAD

**Issue by CheaterHu** [develon2015/Youtube-dl-REST#6]

**Comment by develon2015** [comment]
可能是CloudFlare的问题，建议挂Proxy下载。

**Comment by CheaterHu** [comment]
是挂了代理的，下载最快就只有一百K，而且几分钟就会断开




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Develon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月19日(星期二) 下午4:53
收件人:&nbsp;"develon2015/Youtube-dl-REST"<Youtube-dl-REST@noreply.github.com&gt;;
抄送:&nbsp;"724300087"<724300087@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [develon2015/Youtube-dl-REST] 最近下载好慢怎么回事，时常断开 (#6)





 
可能是CloudFlare的问题，建议挂Proxy下载。
